### ISSUE TITLE
Error launching server

### ISSUE THREAD

**Issue by ghost** [laktek/punch-current-page-helper#1]
I've tried creating a helper using this code in `helpers/current_helper.js` and including the following in the config:

``` json
  "plugins": {
    "helpers": {
      "current_helper": "./helpers/current_helper.js"
    }
  }
```

...but I get the following error:

``` bash
module.js:340
    throw err;
          ^
Error: Cannot find module 'punch'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/path/to/my-project/helpers/current_helper.js:9:20)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
```

Also the `config.json` file doesn't load at all if I have a config directory present (necessary for my deployment code).

**Comment by ghost** [comment]
Got rid of config folder problem by upgrading from 0.5.12 to 0.5.22 but helper still won't load.

**Comment by laktek** [comment]
Sorry the config sample code on README was incorrect. Please try the following:

``` json
"plugins": {
    "helpers": {
      "current_helper": "punch-current-page-helper"
    }
  }
```
